### PR TITLE
A bunch of changes to get the interface up to date.

### PR DESCRIPTION
**Pull request by tilmantroester**
Also added a cmake build system for standalone cosmosis. Old Makefile should still work though.

### CODE REVIEW

**Comment by alexander-mead** [comment]
Okay, that looks great. If you are happy then I am happy. Am I correct in thinking that the only bit that affects me would be your changes in `cosmology_functions.f90`? I see you have promoted `p_lin` to be recursive, I guess that was to make it work in debug mode? Is the new line `cosm%is_normalised=.TRUE.` in `p_lin` necessary? `cosm%is_normalised` gets set to true first thing in `normalise_power`, so it looks unnecessary to me.

**Comment by alexander-mead** [comment]
Looks good. Could you comment on my previous comment regarding `cosm%is_normalised=.TRUE.` and then I can merge?

**Comment by tilmantroester** [comment]
Right. It refused to compile for me without the `recursive`. I set the `cosm%is_normalised=.TRUE.` before calling `normalise_power` to be very sure there is no infinite recursion in case `normalise_power` ever gets changed and the `cosm%is_normalised=.TRUE.` statement in there gets forgotten.

**Comment by alexander-mead** [comment]
Okay, I'll probably remove that, but I understand your concern.

**Comment by tilmantroester** [comment]
Ok. Maybe leave a comment in `p_lin` that states that `normalise_power` calls `p_lin` again and hence there is a recursion to be aware of.

**Pull request merged**
